### ISSUE TITLE
TypeScript issue with latest 0.8.0 version

### ISSUE THREAD

**Issue by mwarger** [get-convex/convex-ents#30]
I have a custom function that looks like this:

```
export const authQuery = customQuery(
  baseQuery,
  customCtx(async (ctx) => {
    const userId = (await ctx.auth.getUserIdentity())?.subject;

    if (!userId) {
      throw new ConvexError('must be logged in');
    }

    const table = entsTableFactory(ctx, entDefinitions);
    const user = await table('users').get('userId', userId);

    if (!user) {
      throw new ConvexError('user not found');
    }

    return {
      table,
      user,
      db: undefined,
    };
  })
);
```

In every version below the latest 0.8.0, this works just fine.  With 0.8.0 I see this error:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/c26e3580-7db6-43ee-a035-269b3a3be7b6">

Something about the latest version is not handling the index types, correctly, as far as I can tell.  Please let me know if there's anything I can do to be more help here.

**Comment by xixixao** [comment]
@mwarger I cannot reproduce it. What does your schema look like?

(if you have time to put together a repo that reproes this issue that'd be ideal)

**Comment by mwarger** [comment]
I will aim to put a reproduction together as soon as I can.  Do you know if convex has a "template example" somewhere where I can just clone it, add my own convex keys and run it?

**Comment by xixixao** [comment]
@mwarger maybe https://github.com/xixixao/saas-starter would work

**Comment by mwarger** [comment]
I believe this ended up being an issue with my version of TypeScript or something.
